version: "3"
services:

  frontend_prod:  
    container_name: frontend_prod
    image: woodychang0611/frontend_prod:1.0.0
    build: 
      context: frontend
      target: prod
      args: 
        SERVER_URL: http://127.0.0.1:${ServerPort:-3456}
    stdin_open: true
    tty: true
    ports:
      - 7080:80
    depends_on:
      - backend

  backend:  
    extends:
      file: ./backend/docker-compose.yaml
      service: backend_prod
