version: "3"
services:
  react_dev:  
    container_name: react_dev
    image: woodychang0611/react_dev:1.0.0
    build: .
    working_dir: /.
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    ports:
      - 5000:5000