version: "3"
services:
  backend_prod:  
    container_name: backend_prod
    image: woodychang0611/backend_prod:1.0.0
    build: 
      context: .
      target: prod
    stdin_open: true
    tty: true
#    env_file:
#      - .env
    environment:
      - ServerPort=${ServerPort:-3456}
    ports:
      - ${ServerPort:-3456}:${ServerPort:-3456}